language: rust
sudo: false
rust:
  # 1.13.0 is the earliest version that Serde 1.0 tests, so we follow suit
  - 1.13.0
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
      env: CLIPPY=n
  include:
    - rust: nightly
      env: CLIPPY=y

env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
    - CLIPPY: n
install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 11
  - nvm use 11
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
script: ./ci/travis.sh
notifications:
  email: false
  irc:
    channels:
      - "irc.mozilla.org#chronotope"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
