language: rust
sudo: false
rust:
  # 1.13.0 is the earliest version that Serde 0.9 tests, so we follow suit
  - 1.13.0
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
script:
  # interleave building and testing in hope that it saves time
  # also vary the local time zone to (hopefully) catch tz-dependent bugs
  # also avoid doc-testing multiple times---it takes a lot and rarely helps
  - cargo build -v
  - TZ=ACST-9:30 cargo test -v
  - cargo build -v --features rustc-serialize
  - TZ=EST4 cargo test -v --features rustc-serialize --lib
  - cargo build -v --features 'serde bincode'
  - TZ=UTC0 cargo test -v --features 'serde bincode' --lib
notifications:
  email: false
  irc:
    channels:
      - "irc.mozilla.org#chronotope"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
